#pragma once
#include "../SnowballProgram.h"
#include "stringhelper.h"
#include <any>
#include <memory>
#include <deque>

// C++ NOTE: Forward class declarations:
#include  "core/src/java/org/tartarus/snowball/Among.h"

// This file was generated automatically by the Snowball to Java compiler

namespace org::tartarus::snowball::ext
{

using Among = org::tartarus::snowball::Among;
using SnowballProgram = org::tartarus::snowball::SnowballProgram;

/**
 * This class was automatically generated by a Snowball to Java compiler
 * It implements the stemming algorithm defined by a snowball script.
 */

// C++ TODO: Most Java annotations will not have direct C++ equivalents:
// ORIGINAL LINE: @SuppressWarnings("unused") public class HungarianStemmer
// extends org.tartarus.snowball.SnowballProgram
class HungarianStemmer : public SnowballProgram
{

private:
  static constexpr int64_t serialVersionUID = 1LL;

  /* patched */
  static const std::shared_ptr<java::lang::invoke::MethodHandles::Lookup>
      methodObject;

  static std::deque<std::shared_ptr<Among>> const a_0;

  static std::deque<std::shared_ptr<Among>> const a_1;

  static std::deque<std::shared_ptr<Among>> const a_2;

  static std::deque<std::shared_ptr<Among>> const a_3;

  static std::deque<std::shared_ptr<Among>> const a_4;

  static std::deque<std::shared_ptr<Among>> const a_5;

  static std::deque<std::shared_ptr<Among>> const a_6;

  static std::deque<std::shared_ptr<Among>> const a_7;

  static std::deque<std::shared_ptr<Among>> const a_8;

  static std::deque<std::shared_ptr<Among>> const a_9;

  static std::deque<std::shared_ptr<Among>> const a_10;

  static std::deque<std::shared_ptr<Among>> const a_11;

  static std::deque<wchar_t> const g_v;

  int I_p1 = 0;

  void copy_from(std::shared_ptr<HungarianStemmer> other);

  bool r_mark_regions();

  bool r_R1();

  bool r_v_ending();

  bool r_double();

  bool r_undouble();

  bool r_instrum();

  bool r_case();

  bool r_case_special();

  bool r_case_other();

  bool r_factive();

  bool r_plural();

  bool r_owned();

  bool r_sing_owner();

  bool r_plur_owner();

public:
  bool stem() override;

  virtual bool equals(std::any o);

  virtual int hashCode();

protected:
  std::shared_ptr<HungarianStemmer> shared_from_this()
  {
    return std::static_pointer_cast<HungarianStemmer>(
        org.tartarus.snowball.SnowballProgram::shared_from_this());
  }
};

} // #include  "core/src/java/org/tartarus/snowball/ext/
