#pragma once
#include "../SnowballProgram.h"
#include "stringhelper.h"
#include <any>
#include <memory>
#include <deque>

// C++ NOTE: Forward class declarations:
namespace org::tartarus::snowball
{
class Among;
}

// This file was generated automatically by the Snowball to Java compiler

namespace org::tartarus::snowball::ext
{

using Among = org::tartarus::snowball::Among;
using SnowballProgram = org::tartarus::snowball::SnowballProgram;

/**
 * This class was automatically generated by a Snowball to Java compiler
 * It implements the stemming algorithm defined by a snowball script.
 */

// C++ TODO: Most Java annotations will not have direct C++ equivalents:
// ORIGINAL LINE: @SuppressWarnings("unused") public class LovinsStemmer extends
// org.tartarus.snowball.SnowballProgram
class LovinsStemmer : public SnowballProgram
{

private:
  static constexpr int64_t serialVersionUID = 1LL;

  /* patched */
  static const std::shared_ptr<java::lang::invoke::MethodHandles::Lookup>
      methodObject;

  static std::deque<std::shared_ptr<Among>> const a_0;

  static std::deque<std::shared_ptr<Among>> const a_1;

  static std::deque<std::shared_ptr<Among>> const a_2;

  static std::deque<std::shared_ptr<Among>> const a_3;

  void copy_from(std::shared_ptr<LovinsStemmer> other);

  bool r_A();

  bool r_B();

  bool r_C();

  bool r_D();

  bool r_E();

  bool r_F();

  bool r_G();

  bool r_H();

  bool r_I();

  bool r_J();

  bool r_K();

  bool r_L();

  bool r_M();

  bool r_N();

  bool r_O();

  bool r_P();

  bool r_Q();

  bool r_R();

  bool r_S();

  bool r_T();

  bool r_U();

  bool r_V();

  bool r_W();

  bool r_X();

  bool r_Y();

  bool r_Z();

  bool r_AA();

  bool r_BB();

  bool r_CC();

  bool r_endings();

  bool r_undouble();

  bool r_respell();

public:
  bool stem() override;

  virtual bool equals(std::any o);

  virtual int hashCode();

protected:
  std::shared_ptr<LovinsStemmer> shared_from_this()
  {
    return std::static_pointer_cast<LovinsStemmer>(
        org.tartarus.snowball.SnowballProgram::shared_from_this());
  }
};

} // namespace org::tartarus::snowball::ext
