#pragma once
#include "stringhelper.h"
/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
namespace org::apache::lucene::queryparser::surround::parser
{

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
class QueryParserConstants
{
  GET_CLASS_NAME(QueryParserConstants)

  /** End of File. */
public:
  static constexpr int EOF = 0;
  /** RegularExpression Id. */
  static constexpr int _NUM_CHAR = 1;
  /** RegularExpression Id. */
  static constexpr int _TERM_CHAR = 2;
  /** RegularExpression Id. */
  static constexpr int _WHITESPACE = 3;
  /** RegularExpression Id. */
  static constexpr int _STAR = 4;
  /** RegularExpression Id. */
  static constexpr int _ONE_CHAR = 5;
  /** RegularExpression Id. */
  static constexpr int _DISTOP_NUM = 6;
  /** RegularExpression Id. */
  static constexpr int OR = 8;
  /** RegularExpression Id. */
  static constexpr int AND = 9;
  /** RegularExpression Id. */
  static constexpr int NOT = 10;
  /** RegularExpression Id. */
  static constexpr int W = 11;
  /** RegularExpression Id. */
  static constexpr int N = 12;
  /** RegularExpression Id. */
  static constexpr int LPAREN = 13;
  /** RegularExpression Id. */
  static constexpr int RPAREN = 14;
  /** RegularExpression Id. */
  static constexpr int COMMA = 15;
  /** RegularExpression Id. */
  static constexpr int COLON = 16;
  /** RegularExpression Id. */
  static constexpr int CARAT = 17;
  /** RegularExpression Id. */
  static constexpr int TRUNCQUOTED = 18;
  /** RegularExpression Id. */
  static constexpr int QUOTED = 19;
  /** RegularExpression Id. */
  static constexpr int SUFFIXTERM = 20;
  /** RegularExpression Id. */
  static constexpr int TRUNCTERM = 21;
  /** RegularExpression Id. */
  static constexpr int TERM = 22;
  /** RegularExpression Id. */
  static constexpr int NUMBER = 23;

  /** Lexical state. */
  static constexpr int Boost = 0;
  /** Lexical state. */
  static constexpr int DEFAULT = 1;

  /** Literal token values. */
  static std::deque<std::wstring> const tokenImage;
};

} // namespace org::apache::lucene::queryparser::surround::parser
